### ISSUE TITLE
Scale not displayed on Iphone X, Xs, Xs Max

### ISSUE THREAD

**Issue by PNepikov** [namshi/NMMultiUnitRuler#1]
![Simulator Screen Shot - iPhone Xs Max - 2019-07-18 at 15 58 17](https://user-images.githubusercontent.com/37261789/61459353-37909200-a975-11e9-9acd-d04a1be5f550.png)

**Comment by noorulain17** [comment]
@PNepikov thank you for reporting. We'll look into it soon.

**Comment by Abdul-Hannan** [comment]
can you please tell us which Xcode version and iOS SDK you are using ?

**Comment by PNepikov** [comment]
Xcode Version 10.2.1 (10E1001)
I notice this issue when testing in the simulator

**Comment by noorulain17** [comment]
@PNepikov what's the OS version of your simulator/device?

**Comment by noorulain17** [comment]
@PNepikov the latest release of `NMMultiUnitRuler - 0.1.1` works fine on iPhone X series devices. Please refer [this](https://raw.githubusercontent.com/namshi/NMMultiUnitRuler/master/Screenshots/NMMultiUnitRuleriPhoneX.png).
